import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { join, relative, sep } from "path";

import { convert } from "html-to-text";
import { parse } from "node-html-parser";

import { docsFlavors, type DocsFlavorId } from "../docsFlavors";
import { contentArtifactsDirectory } from "../contentGraph/staticArtifacts";
import type { ISearchIndexItem } from "./search.utils";
import { getAllFiles } from "./tools";
import { getApiLabel, getTypeDocBasePath, hasTypeDocArtifacts } from "./typedoc.utils";

export const apiSearchIndexFileName = "api-search-index.json";

/**
 * The API pages are static HTML generated by TypeDoc, so their searchable text is
 * extracted at build time instead of being derived from the content graph.
 * Content is capped so a single upload batch stays well below the service request limit.
 */
const MAX_CONTENT_LENGTH = 15000;

export interface ApiSearchIndexTarget {
    baseLocation: string;
    flavorId: DocsFlavorId;
}

export interface ApiSearchIndexArtifact {
    /** Base locations that actually had TypeDoc artifacts when the index was generated. */
    indexedTargets: string[];
    items: ISearchIndexItem[];
}

export const apiSearchIndexTargets: ApiSearchIndexTarget[] = [
    { baseLocation: "typedoc", flavorId: docsFlavors.babylon.id },
    { baseLocation: "packages/viewer", flavorId: docsFlavors.babylon.id },
    // Only generated when the Babylon Lite repository is public.
    { baseLocation: "lite/typedoc", flavorId: docsFlavors.lite.id },
];

/**
 * A flavor may only be cleared from the remote index when the freshly generated index covers
 * every target of that flavor. A partial index would otherwise delete API documents that
 * nothing is going to re-upload.
 */
export const isFlavorFullyIndexed = (artifact: ApiSearchIndexArtifact, flavorId: DocsFlavorId, targets: ApiSearchIndexTarget[] = apiSearchIndexTargets) => {
    const flavorTargets = targets.filter((target) => target.flavorId === flavorId);
    return flavorTargets.length > 0 && flavorTargets.every((target) => artifact.indexedTargets.includes(target.baseLocation));
};

const encodeSearchId = (value: string) => Buffer.from(value, "utf-8").toString("base64");

const getRouteId = (filesPath: string, fileName: string) =>
    relative(filesPath, fileName)
        .replace(/\.html$/, "")
        .split(sep);

export const createTypeDocSearchIndexItem = (html: string, id: string[], baseLocation: string, flavorId: DocsFlavorId): ISearchIndexItem => {
    const root = parse(html);
    const apiLabel = getApiLabel(baseLocation);
    const url = `/${baseLocation}/${id.join("/")}`;

    const titleNode = root.querySelector("head title")?.firstChild;
    const title = titleNode ? titleNode.rawText.split(" | ")[0] : apiLabel;

    const comment = root.querySelector(".tsd-panel .tsd-comment p") ?? root.querySelector(".tsd-comment p");
    const description = `${comment ? comment.textContent.substring(0, 150) : id.join(" ")} [${apiLabel}]`.replace(/[\n\t]/g, "");

    root.querySelectorAll("script").forEach((node) => node.remove());
    const colContent = root.querySelector(".col-content");
    const content = convert(colContent ? colContent.innerHTML : root.toString(), {
        wordwrap: false,
        selectors: [{ selector: "a", options: { ignoreHref: true } }],
    }).substring(0, MAX_CONTENT_LENGTH);

    return {
        id: encodeSearchId(url),
        flavor: flavorId,
        path: url,
        isApi: true,
        title,
        description,
        content,
        keywords: id,
    };
};

export const createTypeDocSearchIndex = (baseLocation: string, flavorId: DocsFlavorId = docsFlavors.babylon.id, basePathResolved: string = getTypeDocBasePath(baseLocation)): ISearchIndexItem[] => {
    const filesPath = join(basePathResolved, "files");
    if (!existsSync(filesPath)) {
        return [];
    }

    return getAllFiles(filesPath, [], ".html")
        .map((fileName) => createTypeDocSearchIndexItem(readFileSync(fileName, "utf-8"), getRouteId(filesPath, fileName), baseLocation, flavorId))
        .sort((left, right) => (left.path ?? "").localeCompare(right.path ?? ""));
};

/**
 * Builds the API search records for every TypeDoc target that has generated artifacts.
 * Targets without artifacts (for example Babylon Lite when the repository is not public) are skipped
 * and reported through `indexedTargets` so consumers can tell a complete index from a partial one.
 */
export const createApiSearchIndex = (targets: ApiSearchIndexTarget[] = apiSearchIndexTargets): ApiSearchIndexArtifact => {
    const artifact: ApiSearchIndexArtifact = { indexedTargets: [], items: [] };

    for (const target of targets) {
        if (!hasTypeDocArtifacts(target.baseLocation)) {
            console.log(`Skipping API search index for ${target.baseLocation} because TypeDoc artifacts are missing.`);
            continue;
        }
        const items = createTypeDocSearchIndex(target.baseLocation, target.flavorId);
        console.log(`API search index: ${items.length} entries for ${target.baseLocation}.`);
        artifact.indexedTargets.push(target.baseLocation);
        artifact.items.push(...items);
    }

    return artifact;
};

export const apiSearchIndexPath = join(contentArtifactsDirectory, apiSearchIndexFileName);

export const writeApiSearchIndex = (artifact: ApiSearchIndexArtifact, outputDirectory: string = contentArtifactsDirectory) => {
    mkdirSync(outputDirectory, { recursive: true });
    const filePath = join(outputDirectory, apiSearchIndexFileName);
    // Written compact: the API index holds the full text of every generated API page.
    writeFileSync(filePath, JSON.stringify(artifact), { encoding: "utf-8" });
    return filePath;
};

export const readApiSearchIndex = (filePath: string = apiSearchIndexPath): ApiSearchIndexArtifact => {
    if (!existsSync(filePath)) {
        return { indexedTargets: [], items: [] };
    }
    return JSON.parse(readFileSync(filePath, "utf-8")) as ApiSearchIndexArtifact;
};

export const buildApiSearchIndex = (targets: ApiSearchIndexTarget[] = apiSearchIndexTargets, outputDirectory: string = contentArtifactsDirectory) => {
    const artifact = createApiSearchIndex(targets);
    const filePath = writeApiSearchIndex(artifact, outputDirectory);
    console.log(`Wrote ${artifact.items.length} API search item(s) from ${artifact.indexedTargets.join(", ") || "no target"} to ${filePath}.`);
    return artifact;
};
